# Generated by Django 4.0.4 on 2022-06-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_balance',
            new_name='amount_transfer',
        ),
        migrations.AlterField(
            model_name='block',
            name='block_hash',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='nounce',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='previous_block_hash',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='transaction_count',
            field=models.IntegerField(null=True),
        ),
    ]
