# Generated by Django 4.0.4 on 2022-06-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchainapp', '0002_rename_account_balance_transaction_amount_transfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='nounce',
            field=models.TextField(null=True),
        ),
    ]
