# Generated by Django 4.0.4 on 2022-09-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(choices=[('PastQ', 'Past Question'), ('handout', 'Handout')], default='PastQ', max_length=50)),
                ('department', models.CharField(choices=[('COM', 'Com Science'), ('ECC', 'Electrical'), ('CET', 'Com engine'), ('STA', 'Statistic'), ('SLT', 'Scn Lab Tech'), ('MAC', 'Mass Com'), ('MMT', 'Mult Media'), ('AGD', 'Graphics'), ('BAM', 'Buss Admin'), ('ACC', 'Accounting'), ('MCB', 'Micro Bio'), ('BCH', 'Biochem')], default='COM', max_length=7)),
            ],
        ),
    ]
