# Generated by Django 4.0.4 on 2022-09-02 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='material',
        ),
    ]
