# Generated by Django 4.0.4 on 2022-09-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_materials_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='course_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='course_title',
            field=models.CharField(default='defual', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='lecturer',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='level',
            field=models.CharField(choices=[('ND1', 'National Deploma 1'), ('ND2', 'National Deploma 2'), ('HND1', 'Higher National Deploma 1'), ('HND2', 'Higher National Deploma 2')], default='ND1', max_length=50),
        ),
        migrations.AddField(
            model_name='materials',
            name='material',
            field=models.CharField(choices=[('PastQ', 'Past Question'), ('handout', 'Handout')], default='PastQ', max_length=50),
        ),
        migrations.AddField(
            model_name='materials',
            name='year',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
