# Generated by Django 4.0.4 on 2022-09-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_materials_course_code_materials_course_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materials',
            old_name='material',
            new_name='material_type',
        ),
    ]
