# Generated by Django 4.0.4 on 2022-09-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_material_materials_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='efile',
            field=models.FileField(default=None, upload_to='media'),
            preserve_default=False,
        ),
    ]
