# Generated by Django 4.0.4 on 2022-09-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_materials_efile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='material_type',
            field=models.CharField(choices=[('PastQ', 'Past Question'), ('handout', 'Handout')], default='handout', max_length=50),
        ),
    ]
