# Generated by Django 4.0.4 on 2022-09-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0002_lecturer_validate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='material',
            field=models.FileField(default=None, upload_to='material'),
            preserve_default=False,
        ),
    ]
