<Controller>
	BoxLayout:
		orientation:"vertical"
		size:root.width, root.height
		padding: 50
		spacing: 20

		Button:
			text:"hello world"

		RoundButton:
			text:"good by"
			pos_hint:{"center_x":0.5}
			size_hint:(1, .3)


<RoundButton@Button>
	background_color:(0,0,0,0)
	background_normal:""
	canvas.before:
		Color:
			rgba:(48/255,84/255,150/25,1)
		RoundedRectangle:
			size: self.size
			pos: self.pos
			radius:[58]


