# Generated by Django 4.0.4 on 2022-08-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_electronicbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicbook',
            name='efile',
            field=models.FileField(upload_to='media'),
        ),
    ]
