# Generated by Django 4.0.4 on 2022-08-30 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_electronicbook_efile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='dept',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
