# Generated by Django 4.0.4 on 2022-08-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_studentuser_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='level',
            field=models.CharField(choices=[('ND1', 'ND1'), ('ND2', 'ND2'), ('HND1', 'HND1'), ('HND2', 'HND2')], default='ND1', max_length=50),
        ),
    ]
