# Generated by Django 4.0.4 on 2022-08-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_studentuser_dept_studentuser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='level',
            field=models.CharField(choices=[('ND1', 'National Deploma 1'), ('ND2', 'National Deploma 2'), ('HND1', 'Higher National Deploma 1'), ('HND2', 'Higher National Deploma 2')], default='ND1', max_length=50),
        ),
    ]
