# Generated by Django 4.0.4 on 2022-09-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studentuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='passport',
            field=models.ImageField(default=None, upload_to='passport'),
            preserve_default=False,
        ),
    ]
